version: '3'

services:
  # Fleet Management Service
  fleet-management:
    build:
      context: ./fleet-management-service/
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fleet-management
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/fleet-management
      - QUARKUS_DATASOURCE_USERNAME=trg
      - QUARKUS_DATASOURCE_PASSWORD=trg
      - QUARKUS_DATASOURCE_DB-KIND=postgresql
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=drop-and-create
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - trg-network
  
  # Car Heartbeat Service
  car-heartbeat:
    build:
      context: ./car-heartbeat-service/
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HEARTBEAT_INTERVAL=10s
      - HEARTBEAT_DELAYED=10s
    networks:
      - trg-network
  
  # Penalty Processing Service
  penalty-processing:
    build:
      context: ./penalty-processing-service/
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8083:8083"
    depends_on:
      - redis
      - postgres
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - trg-network

  # PostgreSQL database
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fleet-management
      POSTGRES_USER: trg
      POSTGRES_PASSWORD: trg
    networks:
      - trg-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    networks:
      - trg-network

  # Kafka broker
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - trg-network

  # ZooKeeper for Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - trg-network

networks:
  trg-network:
    name: trgnetwork
